import * as Sharing from 'expo-sharing';
import { StatusBar } from 'expo-status-bar';
import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Alert, AppState, AppStateStatus, PermissionsAndroid, Platform, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';

import { createJournalExport } from './src/exportJournal';
import { drainNativeMonitorRecords, isIgnoringBatteryOptimizations, isNativeMonitorActive, isNativeMonitorAvailable, requestIgnoreBatteryOptimizations, runNativeMonitorNow, startNativeMonitor, stopNativeMonitor } from './src/nativeMonitor';
import { getManualCheckWaitMs, shouldThrottleManualCheck } from './src/schedulePolicy';
import { appendRecords, countFailuresSince, findLastSuccess, loadRecords } from './src/storage';
import { CanaryRecord } from './src/types';

function formatDate(value?: string): string { return value ? new Date(value).toLocaleString('ru-RU', { timeZone: 'UTC', hour12: false }) : 'нет данных'; }
function resultText(records: CanaryRecord[]): string { const latestRun = records.filter(r => r.testType !== 'missed_cycle').slice(-5); return !latestRun.length ? 'Ожидает первой проверки' : latestRun.every(r => r.success) ? 'Связь есть' : latestRun.some(r => r.success) ? 'Частичная связь' : 'Связи нет'; }

export default function App() {
  const [records, setRecords] = useState<CanaryRecord[]>([]); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const [nowMs, setNowMs] = useState(Date.now()); const [monitoring, setMonitoring] = useState(false); const busyRef = useRef(false);
  const reload = useCallback(async () => { const native = await drainNativeMonitorRecords(); if (native.length) await appendRecords(native); setRecords(await loadRecords()); }, []);
  const runCheck = useCallback(async () => { if (busyRef.current) return; if (!isNativeMonitorAvailable()) { setMessage('Нативный мониторинг доступен только в установленном Android-приложении.'); return; } busyRef.current = true; setBusy(true); try { const nativeRecords = await runNativeMonitorNow(); await appendRecords(nativeRecords); await reload(); setNowMs(Date.now()); setMessage(`Проверка завершена: ${nativeRecords.filter(record => record.success).length} из 5 успешны`); } catch { setMessage('Проверка не выполнена'); } finally { busyRef.current = false; setBusy(false); } }, [reload]);
  useEffect(() => { void reload(); void isNativeMonitorActive().then(setMonitoring).catch(() => setMonitoring(false)); const timer = setInterval(() => setNowMs(Date.now()), 1000); const listener = AppState.addEventListener('change', (state: AppStateStatus) => { if (state === 'active') { setNowMs(Date.now()); void reload(); } }); return () => { clearInterval(timer); listener.remove(); }; }, [reload]);
  const latest = records.at(-1); const lastSuccess = useMemo(() => findLastSuccess(records), [records]); const failures24h = useMemo(() => countFailuresSince(records, new Date(nowMs - 86400000)), [nowMs, records]); const manualWaitMs = getManualCheckWaitMs(latest?.timestampUtc, new Date(nowMs));
  const runManual = useCallback(async () => { if (shouldThrottleManualCheck(latest?.timestampUtc).throttled) { setMessage('Повторная проверка будет доступна через 15 минут.'); return; } await runCheck(); }, [latest?.timestampUtc, runCheck]);
  const toggleMonitor = useCallback(async () => { if (!isNativeMonitorAvailable()) { setMessage('Фоновый мониторинг доступен в Android development build.'); return; } setBusy(true); try { if (monitoring) { await stopNativeMonitor(); setMonitoring(false); setMessage('Фоновый мониторинг остановлен'); return; } if (Platform.OS === 'android' && Number(Platform.Version) >= 33 && await PermissionsAndroid.request(PermissionsAndroid.PERMISSIONS.POST_NOTIFICATIONS) !== PermissionsAndroid.RESULTS.GRANTED) { setMessage('Разреши уведомления: Android постоянно показывает активный мониторинг.'); return; } if (!await isIgnoringBatteryOptimizations()) { Alert.alert('Разрешить работу в фоне?', 'Android может остановить мониторинг. На следующем экране можно исключить Hearth Canary из оптимизации батареи.', [{ text: 'Позже', style: 'cancel' }, { text: 'Открыть настройки', onPress: () => { void requestIgnoreBatteryOptimizations(); } }]); } await startNativeMonitor(); setMonitoring(true); setMessage('Мониторинг активен: примерно каждые 15 минут; уведомление видно в шторке'); } catch { setMessage('Не удалось включить фоновый мониторинг'); } finally { setBusy(false); } }, [monitoring]);
  const exportJournal = useCallback(async () => { setBusy(true); try { const uri = await createJournalExport(); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { mimeType: 'application/json', dialogTitle: 'Отправить журнал Hearth Canary' }); setMessage('Журнал подготовлен для отправки'); } catch { setMessage('Не удалось подготовить журнал'); } finally { setBusy(false); } }, []);
  return <SafeAreaView style={styles.safeArea}><StatusBar style="dark" /><ScrollView contentContainerStyle={styles.container}><Text style={styles.title}>Hearth Canary</Text><View style={styles.panel}><Text style={styles.label}>Текущий результат</Text><Text style={styles.result}>{resultText(records)}</Text><Text style={styles.detail}>Последняя запись: {formatDate(latest?.timestampUtc)} UTC</Text><Text style={styles.detail}>Тип сети: {latest?.networkType ?? 'нет данных'}</Text></View><View style={styles.statsRow}><View style={styles.statBox}><Text style={styles.label}>Последний успех</Text><Text style={styles.statValue}>{formatDate(lastSuccess?.timestampUtc)}</Text></View><View style={styles.statBox}><Text style={styles.label}>Завершено проверок</Text><Text style={styles.statValue}>{records.filter(r => r.testType === 'http_domain').length}</Text><Text style={styles.label}>Ошибки за 24 ч.: {failures24h}</Text></View></View>{message ? <Text style={styles.message}>{message}</Text> : null}<Text style={styles.helpText}>Для отдельного замера мобильной сети один раз выключи Wi‑Fi и нажми «Проверить сейчас».</Text><View style={styles.actions}><Pressable accessibilityRole="button" disabled={busy || manualWaitMs > 0} onPress={runManual} style={({ pressed }) => [styles.primaryButton, (busy || manualWaitMs > 0 || pressed) && styles.buttonPressed]}>{busy ? <ActivityIndicator color="#fff" /> : null}<Text style={styles.primaryButtonText}>Проверить сейчас</Text></Pressable><Pressable accessibilityRole="button" disabled={busy} onPress={toggleMonitor} style={({ pressed }) => [styles.secondaryButton, (busy || pressed) && styles.buttonPressed]}><Text style={styles.secondaryButtonText}>{monitoring ? 'Остановить фоновый мониторинг' : 'Включить фоновый мониторинг'}</Text></Pressable><Pressable accessibilityRole="button" disabled={busy} onPress={exportJournal} style={({ pressed }) => [styles.secondaryButton, (busy || pressed) && styles.buttonPressed]}><Text style={styles.secondaryButtonText}>Отправить журнал</Text></Pressable></View></ScrollView></SafeAreaView>;
}
const styles = StyleSheet.create({ safeArea: { flex: 1, backgroundColor: '#f7f5f0' }, container: { flexGrow: 1, padding: 24, gap: 18 }, title: { color: '#17201b', fontSize: 28, fontWeight: '700' }, panel: { backgroundColor: '#fff', borderColor: '#d9d5cb', borderRadius: 8, borderWidth: 1, padding: 18, gap: 8 }, label: { color: '#58625c', fontSize: 13, fontWeight: '600' }, result: { color: '#0d3b2e', fontSize: 30, fontWeight: '700' }, detail: { color: '#3e4842', fontSize: 15 }, statsRow: { flexDirection: 'row', gap: 12 }, statBox: { flex: 1, minHeight: 104, backgroundColor: '#fff', borderColor: '#d9d5cb', borderRadius: 8, borderWidth: 1, padding: 16, gap: 8 }, statValue: { color: '#17201b', fontSize: 18, fontWeight: '700' }, message: { color: '#26332c', fontSize: 15 }, helpText: { color: '#58625c', fontSize: 13 }, actions: { marginTop: 'auto', gap: 12 }, primaryButton: { minHeight: 52, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 8, backgroundColor: '#116149', borderRadius: 8, paddingHorizontal: 16 }, secondaryButton: { minHeight: 52, alignItems: 'center', justifyContent: 'center', borderColor: '#116149', borderRadius: 8, borderWidth: 1, paddingHorizontal: 16 }, buttonPressed: { opacity: 0.7 }, primaryButtonText: { color: '#fff', fontSize: 16, fontWeight: '700' }, secondaryButtonText: { color: '#116149', fontSize: 16, fontWeight: '700' } });
